name: Deploy to Vercel on Push

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deployment
        run: |
          curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_FYgZxTmbpJkOB0amKWoAEXzBd0Oq/9FP1A8Sli3 \
          -H "Content-Type: application/json" \
          -d '{"name": "deploy"}'
